# Generated by Django 5.1.3 on 2024-11-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='satus',
            field=models.CharField(choices=[('blocked', 'blocked'), ('in_active', 'in_active'), ('in_progress', 'in_progress')], default=None, max_length=25),
        ),
    ]
