# Generated by Django 5.1.3 on 2024-11-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_priority_project_satus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='task',
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='satus',
            field=models.CharField(choices=[('blocked', 'blocked'), ('in_active', 'in_active'), ('in_progress', 'in_progress')], default='in_progress', max_length=25),
        ),
    ]
