# Generated by Django 5.1.3 on 2024-11-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_project_task_alter_project_priority_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.DeleteModel(
            name='project',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
