# Generated by Django 5.1.3 on 2024-11-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='task',
        ),
    ]
