# Generated by Django 5.1.3 on 2024-11-22 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_project_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.task'),
            preserve_default=False,
        ),
    ]
