# Generated by Django 5.1.3 on 2024-11-23 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='satus',
            new_name='status',
        ),
    ]
