# Generated by Django 5.1.3 on 2024-11-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_satus_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', max_length=35),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('blocked', 'blocked'), ('in_active', 'in_active'), ('in_progress', 'in_progress')], default='in_progress', max_length=35),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=400),
        ),
    ]
