# Generated by Django 5.1.3 on 2024-11-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_project_priority_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='task',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
